## Import necessary modules

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import scipy.stats as scs
import os

## Load the data set

In [9]:
pathToData = "/Euro_2020/data"
os.chdir(pathToData)

In [10]:
df = pd.read_csv('euro2020.csv')

In [14]:
pathToBase = "/Euro_2020"
os.chdir(pathToBase)

In [16]:
df.head()

,Player,Country,Position,Match played,Goals,Right foot goals,Left foot goals,Header goals,Assists,Total attempts,...,Top speed,Passing accuracy,Distance covered,Clearence attempted,Balls recovered,Tackels,Blocks,Yellow cards,Red cards,Minutes played
0,Cristiano Ronaldo,Portugal,F,4,5,3.0,2.0,0.0,1.0,16.0,...,29.7,86,36.1,2.0,2.0,1.0,NaN,0.0,0.0,360
1,Patrik Schick,Czech Republic,F,5,5,1.0,3.0,1.0,0.0,16.0,...,32.4,71,43.6,4.0,6.0,3.0,NaN,0.0,0.0,404
2,Karim Benzema,France,F,4,4,2.0,2.0,1.0,0.0,11.0,...,29.5,87,37.1,1.0,4.0,0.0,NaN,0.0,0.0,349
3,Emil Forsberg,Sweden,M,4,4,2.0,2.0,0.0,0.0,14.0,...,29.0,79,41.4,NaN,7.0,NaN,NaN,1.0,0.0,371
4,Romelu Lukaku,Belgium,F,5,4,2.0,2.0,0.0,0.0,13.0,...,31.3,69,40.9,2.0,3.0,0.0,NaN,0.0,0.0,444

In [19]:
df.shape

(59, 27)

## Inspect basic stats information of the data set

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Player               59 non-null     object
 1   Country              59 non-null     object
 2   Position             58 non-null     object
 3   Match played         59 non-null     int64
 4   Goals                59 non-null     int64
 5   Right foot goals     57 non-null     float64
 6   Left foot goals      57 non-null     float64
 7   Header goals         57 non-null     float64
 8   Assists              58 non-null     float64
 9   Total attempts       58 non-null     float64
 10  On target            56 non-null     float64
 11  Off target           56 non-null     float64
 12  Woodwork             55 non-null     float64
 13  Shot blocks          56 non-null     float64
 14  Avg gpg              59 non-null     float64
 15  Fouls suffered       55 non-null     float64
 16  Fouls committed      59 non-null     int64
 17  Top speed            59 non-null     float64
 18  Passing accuracy     59 non-null     int64
 19  Distance covered     59 non-null     float64
 20  Clearence attempted  50 non-null     float64
 21  Balls recovered      55 non-null     float64
 22  Tackels              53 non-null     float64
 23  Blocks               19 non-null     float64
 24  Yellow cards         56 non-null     float64
 25  Red cards            56 non-null     float64
 26  Minutes played       59 non-null     int64
dtypes: float64(19), int64(5), object(3)
memory usage: 12.6+ KB

In [18]:
df.describe()

,Match played,Goals,Right foot goals,Left foot goals,Header goals,Assists,Total attempts,On target,Off target,Woodwork,...,Top speed,Passing accuracy,Distance covered,Clearence attempted,Balls recovered,Tackels,Blocks,Yellow cards,Red cards,Minutes played
count,59.000000,59.000000,57.000000,57.000000,57.000000,58.000000,58.000000,56.000000,56.000000,55.000000,...,59.000000,59.000000,59.000000,50.000000,55.000000,53.000000,19.000000,56.000000,56.0,59.000000
mean,4.813559,1.338983,0.649123,0.456140,0.210526,0.741379,7.620690,2.982143,2.982143,0.218182,...,30.327119,83.711864,46.272881,6.320000,16.327273,4.433962,1.736842,0.482143,0.0,417.796610
std,1.166701,1.504134,0.876096,0.757585,0.490511,1.018433,5.634566,2.673038,2.576051,0.497807,...,1.560927,7.714855,14.160421,7.138399,11.481151,4.873434,2.513123,0.660332,0.0,122.439961
min,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,26.600000,66.000000,18.100000,0.000000,1.000000,0.000000,0.000000,0.000000,0.0,180.000000
25%,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.250000,1.000000,1.000000,0.000000,...,29.500000,79.000000,37.150000,2.000000,5.500000,2.000000,0.000000,0.000000,0.0,359.000000
50%,4.000000,1.000000,0.000000,0.000000,0.000000,0.000000,7.000000,2.500000,2.000000,0.000000,...,30.600000,85.000000,42.300000,4.000000,14.000000,3.000000,1.000000,0.000000,0.0,384.000000
75%,6.000000,2.000000,1.000000,1.000000,0.000000,1.000000,12.000000,5.000000,4.250000,0.000000,...,31.400000,90.000000,52.650000,8.000000,25.000000,6.000000,2.000000,1.000000,0.0,458.000000
max,7.000000,5.000000,3.000000,3.000000,2.000000,4.000000,20.000000,9.000000,9.000000,2.000000,...,33.100000,98.000000,86.600000,29.000000,46.000000,30.000000,8.000000,3.000000,0.0,705.000000

## Extract data of interest from the data set

In [20]:
dfItaly = df[df['Country'] == 'Italy']
dfItaly

,Player,Country,Position,Match played,Goals,Right foot goals,Left foot goals,Header goals,Assists,Total attempts,...,Top speed,Passing accuracy,Distance covered,Clearence attempted,Balls recovered,Tackels,Blocks,Yellow cards,Red cards,Minutes played
13,Lorenzo Insigne,Italy,F,6,2,2.0,0.0,0.0,0.0,19.0,...,30.8,81,61.4,2.0,5.0,2.0,NaN,1.0,0.0,512
15,Ciro Immobile,Italy,F,6,2,2.0,0.0,0.0,1.0,18.0,...,31.7,79,54.4,2.0,4.0,1.0,NaN,0.0,0.0,444
16,Federico Chiesa,Italy,M,7,2,1.0,1.0,0.0,0.0,17.0,...,33.1,80,47.8,2.0,4.0,2.0,NaN,0.0,0.0,438
25,Marco Veratti,Italy,M,5,0,0.0,0.0,0.0,3.0,4.0,...,27.4,93,49.9,1.0,32.0,30.0,NaN,1.0,0.0,400
52,Jorginho,Italy,M,7,0,0.0,0.0,0.0,0.0,0.0,...,27.7,93,86.6,4.0,46.0,11.0,NaN,1.0,0.0,705
53,Giorgio Chiellini,Italy,D,5,0,0.0,0.0,0.0,0.0,2.0,...,29.0,90,47.4,23.0,37.0,3.0,2.0,1.0,0.0,444
54,Leonardo Bonucci,Italy,D,7,1,0.0,1.0,0.0,0.0,5.0,...,29.9,89,66.1,18.0,26.0,1.0,3.0,2.0,0.0,675

In [21]:
dfSpain = df[df['Country'] == 'Spain']
dfSpain

,Player,Country,Position,Match played,Goals,Right foot goals,Left foot goals,Header goals,Assists,Total attempts,...,Top speed,Passing accuracy,Distance covered,Clearence attempted,Balls recovered,Tackels,Blocks,Yellow cards,Red cards,Minutes played
11,Alvaro Morata,Spain,F,6,3,1.0,2.0,0.0,0.0,16.0,...,31.0,79,52.9,NaN,NaN,NaN,NaN,0.0,0.0,452
17,Ferran Torres,Spain,M,6,2,NaN,NaN,NaN,1.0,8.0,...,30.8,83,39.5,NaN,9.0,2.0,NaN,NaN,NaN,366
24,Dani Olmo,Spain,M,5,0,0.0,0.0,0.0,3.0,20.0,...,28.6,77,42.6,NaN,6.0,1.0,NaN,0.0,0.0,379
26,Jordi Alba,Spain,D,6,0,0.0,0.0,0.0,2.0,2.0,...,31.5,86,64.2,7.0,33.0,4.0,0.0,1.0,0.0,553
55,Aymeric Laporte,Spain,D,6,1,0.0,0.0,1.0,0.0,2.0,...,30.4,96,65.9,17.0,31.0,8.0,2.0,1.0,0.0,630

In [22]:
dfEngland = df[df['Country'] == 'England']
dfEngland

,Player,Country,Position,Match played,Goals,Right foot goals,Left foot goals,Header goals,Assists,Total attempts,...,Top speed,Passing accuracy,Distance covered,Clearence attempted,Balls recovered,Tackels,Blocks,Yellow cards,Red cards,Minutes played
5,Harry Kane,England,F,7,4,2.0,0.0,2.0,0.0,15.0,...,30.8,72,74.3,5.0,4.0,3.0,NaN,0.0,0.0,649
7,Raheem Sterling,England,F,7,3,2.0,0.0,1.0,1.0,14.0,...,33.1,84,68.3,1.0,14.0,0.0,NaN,0.0,0.0,641
23,Luke Shaw,England,D,6,1,0.0,1.0,0.0,3.0,3.0,...,31.0,83,62.7,8.0,21.0,9.0,1.0,0.0,0.0,575
27,John Stones,England,D,7,0,0.0,0.0,0.0,0.0,5.0,...,29.7,94,67.3,17.0,33.0,3.0,8.0,0.0,0.0,679
28,Kalvin Phillips,England,M,7,0,0.0,0.0,0.0,1.0,4.0,...,30.2,87,83.0,10.0,32.0,13.0,NaN,1.0,0.0,665
29,Harry Maguire,England,D,5,1,0.0,0.0,1.0,0.0,8.0,...,30.6,92,51.5,29.0,34.0,6.0,4.0,3.0,0.0,510
30,Mason Mount,England,M,5,0,0.0,0.0,0.0,1.0,7.0,...,31.5,85,50.4,1.0,11.0,2.0,NaN,0.0,0.0,464